include:
  - project: secure-templates/trivy
    file: /trivy.gitlab-ci.yml
  - project: secure-templates/gitleaks
    file: /gitleaks.gitlab-ci.yml

stages:
  - container_scanning
  - code_scanning
  - gitleaks_scan
  - helm_scan

helm_lint:
  stage: helm_scan
  image: harbor.ops.quest/docker-hub-proxy/alpine/helm:3.12.0
  script:
    - helm lint . -f values.yaml --set "secrets.actualPassword=dummy" --set "secrets.ebApplicationId=dummy" --set "secrets.ebRedirectUrl=dummy" --set "ebImporter.config.actualAccountId=dummy" --set-file "secrets.ebPrivateKey=text.txt" --set "secrets.smtpPassword=dummy"
  only:
    - merge_requests
    - main