apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terra-budget.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.actualBudget.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.actualBudget.storage.size }}
