apiVersion: v1
kind: Secret
metadata:
  name: eb-importer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terra-budget.labels" . | nindent 4 }}
type: Opaque
data:
  actual-password: {{ .Values.secrets.actualPassword | b64enc | quote }}
  private.pem: {{ .Values.secrets.ebPrivateKey | b64enc | quote }}
  config.json: {{ printf "{\"applicationId\":%q,\"redirectUrl\":%q}" .Values.secrets.ebApplicationId .Values.secrets.ebRedirectUrl | b64enc | quote }}
  {{- if .Values.secrets.smtpPassword }}
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc | quote }}
  {{- end }}
