apiVersion: v1
kind: Service
metadata:
  name: actual-budget
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terra-budget.labels" . | nindent 4 }}
spec:
  selector:
    app: actual-budget
  ports:
    - port: 5006
      targetPort: 5006
  type: ClusterIP
